# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: To be professional
email: me.noproblemo@gmail.com
description: ""
baseurl: "Learn Front and Back react and react native and jquery php" # the subpath of your site, e.g. /blog
url: "http://noproblemo.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  noproblemo
timezone:    Aisa/Seoul

# Build settings
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
  syntax_highlighter: rouge

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
